In [1]:
#不带参数的层
import torch
import torch.nn.functional as F
from torch import nn


class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()#先计算输入 `X` 的平均值- 再让输入里的每个元素都减去这个平均值

In [2]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [4]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(1.3970e-09, grad_fn=<MeanBackward0>)

In [5]:
#带参数的层
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [6]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.9708,  1.4313,  0.9336],
        [ 0.6551, -0.6664,  0.4833],
        [ 0.3794,  0.8991, -0.8843],
        [ 2.2428,  0.4926,  0.4280],
        [-0.6146, -1.9461, -0.1787]], requires_grad=True)

In [7]:
linear(torch.rand(2, 5))

tensor([[0.7439, 0.0000, 1.1730],
        [0.5192, 0.0859, 0.6098]])

In [8]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.0000],
        [6.5342]])